=== Karan0620/eightfold-candidate-transformer/src/schema/candidateSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",

  "properties": {

    "candidate_id": {
      "type": "string"
    },

    "full_name": {
      "type": "string"
    },

    "emails": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },

    "phones": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },

    "skills": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },

    "experience": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": { "type": ["string", "null"] },
          "company": { "type": ["string", "null"] },
          "duration": { "type": ["string", "null"] },
          "location": { "type": ["string", "null"] }
        }
      }
    },

    "education": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },

    "overall_confidence": {
      "type": "number"
    },

    "provenance": {
      "type": "object"
    }

  },

  "required": [
    "candidate_id",
    "full_name",
    "emails",
    "phones",
    "skills"
  ]
}

=== Karan0620/eightfold-candidate-transformer/output/candidate.json
{
  "candidate_id": "6ae6b0f1-f623-487e-9cb8-95a99498995e",
  "full_name": "KARAN ASWANI",
  "emails": [
    "karanaswani0620@gmail.com",
    "karan.aswani@gmail.com"
  ],
  "phones": [
    "+919039630009",
    "+919876543210"
  ],
  "skills": [
    "Java",
    "JavaScript",
    "SQL",
    "Spring Boot",
    "Node.js",
    "Express.js",
    "REST APIs",
    "React.js",
    "MySQL",
    "MongoDB",
    "OOP",
    "Collections Framework",
    "Exception Handling",
    "Multithreading",
    "JDBC",
    "Data Structures & Algorithms",
    "DBMS",
    "Operating Systems",
    "SDLC",
    "Agile Methodologies",
    "Git",
    "GitHub",
    "Playwright",
    "Rest Assured",
    "Datadog"
  ],
  "experience": [
    {
      "title": "Software Development Intern",
      "company": "Vena Solutions Software India Pvt. Ltd.",
      "duration": "February 2026 – June 2026",
      "location": "Full-Time Onsite, Indore, Madhya Pradesh"
    }
  ],
  "education": [
    "B.TECH. — Computer Science & Engineering | Medicaps University | CGPA: 8.79 / 10.0 | 2022 – 2026",
    "Senior Secondary (Class XII) | CBSE Board | Percentage: 90% | 2022",
    "Secondary (Class X) | CBSE Board | Percentage: 90% | 2020"
  ],
  "overall_confidence": 1,
  "provenance": {
    "full_name": [
      "resume",
      "csv"
    ],
    "emails": [
      "resume",
      "csv"
    ],
    "phones": [
      "resume",
      "csv"
    ],
    "skills": [
      "resume",
      "csv"
    ],
    "experience": [
      "resume"
    ],
    "education": [
      "resume"
    ],
    "headline": [],
    "location": [],
    "links": []
  }
}
